-- MySQL Script generated by MySQL Workbench
-- 04/18/17 23:53:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Sist_Inventario
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Sist_Inventario
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Sist_Inventario` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema proyecto
-- -----------------------------------------------------
USE `Sist_Inventario` ;

-- -----------------------------------------------------
-- Table `Sist_Inventario`.`TIPO_ACTIVO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sist_Inventario`.`TIPO_ACTIVO` (
  `id_activo` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_activo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sist_Inventario`.`ESTADO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sist_Inventario`.`ESTADO` (
  `id_estado` INT NOT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sist_Inventario`.`EMPRESA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sist_Inventario`.`EMPRESA` (
  `id_empresa` INT NOT NULL,
  `ruc` VARCHAR(30) NOT NULL,
  `razon_social` VARCHAR(200) NOT NULL,
  `rubro` VARCHAR(60) NULL,
  `direccion` VARCHAR(200) NULL,
  `representante` VARCHAR(100) NULL,
  `tipo` VARCHAR(60) NULL,
  `id_estado` INT NOT NULL,
  PRIMARY KEY (`id_empresa`),
  INDEX `fk_id_estado_idx` (`id_estado` ASC),
  CONSTRAINT `fk_id_estado_E`
    FOREIGN KEY (`id_estado`)
    REFERENCES `Sist_Inventario`.`ESTADO` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sist_Inventario`.`ESTADO_ACTIVO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sist_Inventario`.`ESTADO_ACTIVO` (
  `id_estado` INT NOT NULL,
  `nombre` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sist_Inventario`.`ACTIVO_P`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sist_Inventario`.`ACTIVO_P` (
  `id_padre` INT NOT NULL,
  `codigo` VARCHAR(9) NOT NULL,
  `id_nombre` INT NOT NULL,
  `id_estado` INT NULL,
  `marca` VARCHAR(45) NULL,
  `id_empresa` INT NULL,
  `id_proveedor` INT NULL,
  `tiempo_de_vida` VARCHAR(45) NULL,
  `modelo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_padre`),
  INDEX `fk_activo_tipoActivo_idx` (`id_nombre` ASC),
  INDEX `fk_id_empresa_idx` (`id_empresa` ASC),
  INDEX `fk_id_proveedor_idx` (`id_proveedor` ASC),
  INDEX `fk_id_estado_idx` (`id_estado` ASC),
  CONSTRAINT `fk_activo_tipoActivo_P`
    FOREIGN KEY (`id_nombre`)
    REFERENCES `Sist_Inventario`.`TIPO_ACTIVO` (`id_activo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_empresa_P`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `Sist_Inventario`.`EMPRESA` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_proveedor_P`
    FOREIGN KEY (`id_proveedor`)
    REFERENCES `Sist_Inventario`.`EMPRESA` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_estado_P`
    FOREIGN KEY (`id_estado`)
    REFERENCES `Sist_Inventario`.`ESTADO_ACTIVO` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sist_Inventario`.`ACTIVO_H1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sist_Inventario`.`ACTIVO_H1` (
  `id_padre` INT NOT NULL,
  `ram` INT NULL,
  `disco_duro` INT NULL,
  `ACTIVO_H1col` VARCHAR(45) NULL,
  `procesador` VARCHAR(100) NULL,
  `direccion_ip` VARCHAR(60) NULL,
  `direccion_mac` VARCHAR(60) NULL,
  `nombre_equipo` VARCHAR(60) NULL,
  `dominio` VARCHAR(60) NULL,
  `tarjeta_video` VARCHAR(50) NULL,
  `sistema_operativo` VARCHAR(60) NULL,
  `tipo_sistema` INT NULL,
  PRIMARY KEY (`id_padre`),
  CONSTRAINT `id_padre_H1`
    FOREIGN KEY (`id_padre`)
    REFERENCES `Sist_Inventario`.`ACTIVO_P` (`id_padre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sist_Inventario`.`ACTIVO_H2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sist_Inventario`.`ACTIVO_H2` (
  `id_padre` INT NOT NULL,
  `pulgadas` INT NULL,
  PRIMARY KEY (`id_padre`),
  CONSTRAINT `id_padre_H2`
    FOREIGN KEY (`id_padre`)
    REFERENCES `Sist_Inventario`.`ACTIVO_P` (`id_padre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sist_Inventario`.`ACTIVO_H3`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sist_Inventario`.`ACTIVO_H3` (
  `id_padre` INT NOT NULL,
  `tipo_puerto` VARCHAR(50) NULL,
  PRIMARY KEY (`id_padre`),
  CONSTRAINT `id_padre_H3`
    FOREIGN KEY (`id_padre`)
    REFERENCES `Sist_Inventario`.`ACTIVO_P` (`id_padre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sist_Inventario`.`ACTIVO_H4`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sist_Inventario`.`ACTIVO_H4` (
  `id_padre` INT NOT NULL,
  `cantidad_puertos` VARCHAR(45) NULL,
  `mac` VARCHAR(45) NULL,
  PRIMARY KEY (`id_padre`),
  CONSTRAINT `id_padre_H4`
    FOREIGN KEY (`id_padre`)
    REFERENCES `Sist_Inventario`.`ACTIVO_P` (`id_padre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sist_Inventario`.`ACTIVO_H5`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sist_Inventario`.`ACTIVO_H5` (
  `id_padre` INT NOT NULL,
  `tamaño_espacio` VARCHAR(50) NULL,
  PRIMARY KEY (`id_padre`),
  CONSTRAINT `id_padre_H5`
    FOREIGN KEY (`id_padre`)
    REFERENCES `Sist_Inventario`.`ACTIVO_P` (`id_padre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sist_Inventario`.`ACTIVO_H6`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sist_Inventario`.`ACTIVO_H6` (
  `id_padre` INT NOT NULL,
  `numero_serie_base` VARCHAR(45) NULL,
  `tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_padre`),
  CONSTRAINT `id_padre_H6`
    FOREIGN KEY (`id_padre`)
    REFERENCES `Sist_Inventario`.`ACTIVO_P` (`id_padre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sist_Inventario`.`TIPO_MOVIMIENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sist_Inventario`.`TIPO_MOVIMIENTO` (
  `id_tipo_movimiento` INT NOT NULL,
  `tipo_movimiento` VARCHAR(100) NOT NULL,
  `id_estado` INT NOT NULL,
  PRIMARY KEY (`id_tipo_movimiento`),
  INDEX `fk_id_estado_idx` (`id_estado` ASC),
  CONSTRAINT `fk_id_estado_TM`
    FOREIGN KEY (`id_estado`)
    REFERENCES `Sist_Inventario`.`ESTADO` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sist_Inventario`.`MARCA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sist_Inventario`.`MARCA` (
  `id_marca` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `id_empresa` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `id_estado` INT NOT NULL,
  PRIMARY KEY (`id_marca`),
  INDEX `id_empresa_idx` (`id_empresa` ASC),
  INDEX `fk_id_estado_idx` (`id_estado` ASC),
  CONSTRAINT `fk_id_empresa_1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `Sist_Inventario`.`EMPRESA` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_estado_1`
    FOREIGN KEY (`id_estado`)
    REFERENCES `Sist_Inventario`.`ESTADO` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sist_Inventario`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sist_Inventario`.`USUARIO` (
  `id_usuario` INT NOT NULL,
  `tipo_documento` VARCHAR(30) NULL,
  `numero_documento` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `a_paterno` VARCHAR(50) NOT NULL,
  `a_materno` VARCHAR(50) NULL,
  `nacimiento` DATE NULL,
  `sexo` CHAR(2) NULL,
  `pais` VARCHAR(50) NULL,
  `departamento` VARCHAR(50) NULL,
  `ciudad` VARCHAR(50) NULL,
  `distrito` VARCHAR(50) NULL,
  `direccion` VARCHAR(200) NULL,
  `correo` VARCHAR(150) NULL,
  `telefono` VARCHAR(50) NULL,
  `celular` VARCHAR(50) NULL,
  `id_empresa` INT NOT NULL,
  `area` VARCHAR(50) NOT NULL,
  `cargo` VARCHAR(50) NULL,
  `inicio` DATE NULL,
  `id_estado` INT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuario_estado_idx` (`id_estado` ASC),
  INDEX `fk_ususario_empresa_idx` (`id_empresa` ASC),
  CONSTRAINT `fk_usuario_estado`
    FOREIGN KEY (`id_estado`)
    REFERENCES `Sist_Inventario`.`ESTADO` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ususario_empresa`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `Sist_Inventario`.`EMPRESA` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sist_Inventario`.`MOVIMIENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sist_Inventario`.`MOVIMIENTO` (
  `id_movimiento` INT NOT NULL,
  `id_tipo_movimiento` INT NOT NULL,
  `fecha_movimiento` DATE NULL,
  `num_guia` VARCHAR(50) NULL,
  `origen` VARCHAR(50) NOT NULL,
  `destino` VARCHAR(50) NOT NULL,
  `id_usuario_respo` INT NOT NULL,
  `id_usuario_recep` INT NOT NULL,
  `observacion` VARCHAR(200) NULL,
  PRIMARY KEY (`id_movimiento`),
  INDEX `fk_movimiento_tipo_movimiento_idx` (`id_tipo_movimiento` ASC),
  INDEX `fk_movimiento_usuario_respo_idx` (`id_usuario_respo` ASC),
  INDEX `fk_movimiento_usuario_recep_idx` (`id_usuario_recep` ASC),
  CONSTRAINT `fk_movimiento_tipo_movimiento`
    FOREIGN KEY (`id_tipo_movimiento`)
    REFERENCES `Sist_Inventario`.`TIPO_MOVIMIENTO` (`id_tipo_movimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimiento_usuario_respo`
    FOREIGN KEY (`id_usuario_respo`)
    REFERENCES `Sist_Inventario`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimiento_usuario_recep`
    FOREIGN KEY (`id_usuario_recep`)
    REFERENCES `Sist_Inventario`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sist_Inventario`.`TIENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sist_Inventario`.`TIENDA` (
  `id_tienda` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `id_marca` INT NOT NULL,
  `id_estado` INT NOT NULL,
  PRIMARY KEY (`id_tienda`),
  INDEX `fk_tienda_marca_idx` (`id_marca` ASC),
  INDEX `fk_tienda_estado_idx` (`id_estado` ASC),
  CONSTRAINT `fk_tienda_marca`
    FOREIGN KEY (`id_marca`)
    REFERENCES `Sist_Inventario`.`MARCA` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tienda_estado`
    FOREIGN KEY (`id_estado`)
    REFERENCES `Sist_Inventario`.`ESTADO` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Sist_Inventario`.`ACCESO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Sist_Inventario`.`ACCESO` (
  `id_acceso` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  `password` VARCHAR(50) NOT NULL,
  `tipo` INT NOT NULL,
  `id_estado` INT NOT NULL,
  `imagen` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_acceso`),
  INDEX `fk_usuario_acceso_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_usuario_acceso`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `Sist_Inventario`.`USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

---me falto este FK:
ALTER TABLE acceso 
ADD CONSTRAINT fk_acceso_estado_1
FOREIGN KEY (id_estado) 
REFERENCES estado (id_estado) 
ON DELETE NO ACTION 
ON UPDATE NO ACTION ;

ALTER TABLE marca 
ADD CONSTRAINT fk_marca_estado_1
FOREIGN KEY (id_usuario) 
REFERENCES usuario (id_usuario) 
ON DELETE NO ACTION 
ON UPDATE NO ACTION;

--Me falto el campo
alter table activo_p add numero_serie varchar(30) null
